Added some experimental functions to the public API
FirelyTeam/firely-validator-api pull request #262
Opened 2024-01-19 14:39 UTC by mmsmits

2024-01-19 16:32 UTC, ewoutkramer requested changes
Some minor glitches, certainly in relation to the size of the PR ;-)

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation.Compilation.Shared/IsExternalInit.cs
> +#if NET8_0_OR_GREATER
That's search & replace for ya ;-)

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/BasicValidator.cs
> +    public abstract class BasicValidator : IValidatable
This should also have an Obsolete construct, otherwise you could in theory start deriving from it and then we're breaking our promise!

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/BindingValidator.cs
> +            [EnumLiteral("required", "http://hl7.org/fhir/binding-strength"), System.ComponentModel.Description("Required")]
That's the wrong namespace, it's `Description` from the `Hl7.Fhir.Utility` namespace. Not that it matters, as this is a copy from code generated in the SDK, where it does matter. But still, we should keep this intact and correct.

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SchemaReferenceValidator.cs
> +    public class SchemaReferenceValidator : IGroupValidatable
Missing Obsolete construct?

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/AssertionValidators.cs
> +    public static class AssertionValidators
Missing Obsolete construct?

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/PublicAPI.Unshipped.txt
> +Firely.Fhir.Validation.AggregationMode
I don't think we have protected the `enum`s with `[Obsolete]`, but I think the message is clear.

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/IsExternalInit.cs
> +#if NET8_0_OR_GREATER
That's a copy & paste error

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Support/IScopedNodeExtensions.cs
> +        public static bool Matches(this IScopedNode value, ITypedElement pattern)
This should be `internal`, just like the function below. My mistake, came from my branch that you merged.

2024-01-19 16:32 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Support/ScopedNodeJsonExtensions.cs
> +        public static JToken ToJToken(this IScopedNode instance)
According to my editor, this function is no longer in use, we can remove it.

2024-01-19 16:32 UTC, ewoutkramer commented on test/Firely.Fhir.Validation.Compilation.Tests.Shared/IsExternalInit.cs
>      internal static class IsExternalInit
Copy & Paste mistake, this came from Microsoft's code and should not be made obsolete.

2024-01-22 13:56 UTC, mmsmits commented on test/Firely.Fhir.Validation.Tests/Support/IValidatableExtensions.cs
> +            ArgumentNullException.ThrowIfNull(input);
We use this in the cardinality and binding validator tests. 
These extension methods are also only for tests purposes

2024-01-22 14:16 UTC, merged