Fixes #298
FirelyTeam/firely-validator-api pull request #360
Opened 2024-09-12 15:25 UTC by mmsmits

Could've been a much prettier check, but now it's readable and understable I think.
Do you agree?

2024-09-13 09:23 UTC, ewoutkramer requested changes

2024-09-13 09:23 UTC, ewoutkramer commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/TypeReferenceBuilder.cs
> +            //there are no profile details and no children, so we don't need to validate against the type reference, because the whole type is already defined by the profile, and will be automaticall
Must be "There are no profile details, but we have children.."

And I suggest:  "because the whole type is already included as children in this profiled element...."

2024-09-13 09:23 UTC, ewoutkramer commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/TypeReferenceBuilder.cs
> +            //if there are multiple types (value[x]), we should always validate against the type references.
This is the crux. It's not immediately clear for the reader why this is so.  If there are multiple types but there are also children, we want to a) validate the children and b) also validate the references. That is what we want to say, right?

2024-09-13 09:48 UTC, mmsmits commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/TypeReferenceBuilder.cs
> +            //if there are multiple types (value[x]), we should always validate against the type references.
Yes, I will add that.

2024-09-13 09:50 UTC, mmsmits commented
Is this clear enough?

2024-09-16 11:16 UTC, ewoutkramer approved these changes

2024-09-16 11:16 UTC, merged