Added validation for the context of extensions
FirelyTeam/firely-validator-api pull request #361
Opened 2024-09-18 08:12 UTC by Kasdejong

## Description
The validator should now (finally) validate extension contexts against their expected context.

## Related issues
Closes #267 

## Tests
Added tests for all possible extension contexts

2024-09-24 09:54 UTC, Kasdejong commented
We have an issue here (Apart from the fact that I seem to have done something weird with the subrepo). We do not step into every profile we encounter. This makes sense for some cases, except it makes verifying whether we are in the correct Element a lot harder, and as a bonus, I believe omitting it is a wrong assumption.

In a separate branch, I created a Patient with a link (backboneElement) with multiple id's and, lo and behold, the validation is a success! I believe us not invoking the profile of backboneElement is a mistake here. This would require quite a big change to the validator though, but it would make my work a LOT easier. I will leave this branch for now until we have discussed this internally.

2024-10-02 15:51 UTC, ewoutkramer requested changes

2024-10-02 15:51 UTC, ewoutkramer commented on .idea/.idea.Firely.Validator.API/.idea/projectSettingsUpdater.xml
> +    <option name="vcsConfiguration" value="3" />
We should Git .ignore this file

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/ExtensionContextBuilder.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
Do we need this pragma?

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/TypeReferenceBuilder.cs
> +                if (def.Type.SingleOrDefault()?.Code is { } tc)
This is very tricky code, so please add so comments on what and why we are doing this.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +    internal List<TypedContext> Contexts { get; }
These members must be serializable (which I think they are), and marked as `[DataMember]` and use `IReadOnlyCollection<>`, see `ElementSchema.cs` for an example.

Note: they must be serializable since another project of ours (the CAR factory) serializes the element schemas to a sqlite database.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/FhirPathValidator.cs
> +        internal InvariantResult RunInvariant(ScopedNode input, ValidationSettings vc, ValidationState s, params (string key, IEnumerable<ITypedElement> value)[] env)
Is there a way to avoid the copy & paste?  It seems only the environment differs....

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +            public string? Id { get; private set; }
This needs `[DataMember]` too.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +            public string? Id { get; private set; }
How Is this different from the name?

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +            public JToken ToJson() =>
Shouldn't the new `id` be in here too?

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +                    .Select(sliceCase => sliceCase.Assertion)
Just checking the first assertion should do, right?

2024-10-02 15:51 UTC, ewoutkramer commented on test/Firely.Fhir.Validation.Compilation.Tests.R4/SchemaSnaps/Bundle.json
> +      "baseRef": "BackboneElement",
This is not a ref, so maybe "baseType" ?

2024-10-02 15:51 UTC, ewoutkramer commented on test/Firely.Fhir.Validation.Compilation.Tests.R4/SchemaSnaps/ProfiledObservation.json
> +      "baseRef": "BackboneElement",
Shouldn't the slices have a baseRef too?

2024-10-02 15:51 UTC, ewoutkramer commented on test/Firely.Fhir.Validation.Compilation.Tests.Shared/ValidationIntegrationTests.cs
> +            var overwrite = true;
This should be returned to false.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/DefinitionPath.cs
> +            var match = new Regex("^(?<type>[A-Za-z]*).?(?<location>.*)$").Match(contextEid);
For regexes that we use unaltered multiple times, you'd better cache the compiled regex, see https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-regex#static-regular-expressions

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/DefinitionPath.cs
> +            var locationComponents = location == "" ? [] : location.Split('.', ':');
`location.Split('.',':', StringSplitOptions.RemoveEmptyEntries)` will do the same without the empty check. If you want to do an empty check, use `String.Empty` instead of `""` to avoid creating empty strings.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/DefinitionPath.cs
> +                ChildNavEvent cne => cne.ChildName == location.Last() && matchesContext(current.Previous, type, location[..^1]),
Maybe `Span<T>` works more efficiently here in these recursive calls?

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/DefinitionPath.cs
> +                    ChildNavEvent cne => cne.Type == type || type == "Element",
Can you give concrete examples of the extension paths you are matching? This will make this easier to read in a few years or so ;-)

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/PathStack.cs
> +        public string? Type { get; }
Maybe `internal` because we don't print it either.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Schema/PathStack.cs
> +        public string Type { get; }
Idem

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +                    "Extension context type was not set, but a context was defined. Skipping non-invariant context validation")
Shouldn't we report this in the constructor? Then we can catch it before we ship the validation to the client.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +                failedInvariantResults
If you don't want to repeat the `fr.Report is not null`, you can also group by `fr.Report is not null` ;-).  You'll get a group `true` and `false` and then you can run the different behaviours, instead of the concat.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +            ContextType.EXTENSION => contextNode.InstanceType == "Extension" && (contextNode.Parent?.Children("url").SingleOrDefault()?.Value as string ?? "None") == context.Expression,
Maybe use a more random magic string (null would also not match btw).

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +        var fhirPathValidator = new FhirPathValidator("ctx-inv", invariant.Replace("%extension", "%%extension"));
Document that we use `%%extension` in our fhirpath dialect, so we need to replace this.

2024-10-02 15:51 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +        var fhirPathValidator = new FhirPathValidator("ctx-inv", invariant.Replace("%extension", "%%extension"));
Or do we need to change this in our FP implementation?

2024-10-03 13:41 UTC, Kasdejong commented on src/Firely.Fhir.Validation.Compilation.Shared/SchemaBuilders/ExtensionContextBuilder.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
I'm afraid there are so many obsolete classes here that we do

2024-10-03 13:57 UTC, Kasdejong commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +            public JToken ToJson() =>
Turns out Id is unused. I simply forgot to remove the property.

2024-10-03 13:59 UTC, Kasdejong commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +                    .Select(sliceCase => sliceCase.Assertion)
The first assertion is not always an elementschema as far as I'm aware. In fact, I've seen "unknown type" get triggered at times. I'm not sure what happens here.

2024-10-08 08:46 UTC, Kasdejong commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +                    "Extension context type was not set, but a context was defined. Skipping non-invariant context validation")
We can still validate invariants. What should we do here?

2024-10-14 08:08 UTC, ewoutkramer requested changes

2024-10-14 08:08 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +                    "Extension context type was not set, but a context was defined. Skipping non-invariant context validation")
I design principle for the validator is that by the time we are validating, we do not report errors anymore about the quality of the profile itself, otherwise put, we cannot bother the end user (who is merely expecting issues about his/her/their instance) with errors that need to be corrected by the author of the profile.  So, we should report this error during compilation.

What we could do (but I don't know that we did it before), is give a WARNING during compilation (which I don't think we can yet), that without this set, only half of the validation will be done. But for now, we should be strict. An incorrect extension context should be flagged as far as I am concerned.

2024-10-14 08:08 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +        var fhirPathValidator = new FhirPathValidator("ctx-inv", invariant.Replace("%extension", "%%extension"));
I think we should. For 5.x we should then accept both. But it will; fix this.

2024-10-14 08:08 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/SliceValidator.cs
> +                    .Select(sliceCase => sliceCase.Assertion)
Ok, we should understand this before putting it into production, so let's go over it one more time.

2024-10-14 08:08 UTC, ewoutkramer commented on src/Firely.Fhir.Validation/Impl/baseType.cs
> +public class baseType : IAssertion
Every type name should start with a captial letter.

2024-10-14 12:16 UTC, Kasdejong commented on src/Firely.Fhir.Validation/Impl/ExtensionContextValidator.cs
> +        var fhirPathValidator = new FhirPathValidator("ctx-inv", invariant.Replace("%extension", "%%extension"));
https://github.com/FirelyTeam/firely-net-sdk/issues/2911

2024-10-18 14:05 UTC, ewoutkramer approved these changes

2024-10-18 14:26 UTC, merged